# Generated by Django 5.2.15 on 2026-06-26 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('location_display', models.CharField(blank=True, max_length=200)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('timezone_auto', models.BooleanField(default=False)),
                ('units', models.CharField(choices=[('metric', 'Metric (km, m)'), ('imperial', 'Imperial (mi, ft)')], default='metric', max_length=10)),
                ('min_score_threshold', models.IntegerField(default=40)),
                ('disq_max_cloud_cover', models.IntegerField(default=85)),
                ('disq_max_precip_prob', models.IntegerField(default=40)),
                ('disq_min_visibility_km', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'starwolf_user_preferences',
            },
        ),
    ]
