# Generated by Django 5.2.15 on 2026-06-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_best_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('planet', 'Planet'), ('star', 'Star'), ('dso', 'Deep Sky Object'), ('meteor_shower', 'Meteor Shower'), ('satellite', 'Satellite')], db_index=True, max_length=20)),
                ('obj_type', models.CharField(blank=True, max_length=50)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('ra_h', models.FloatField(blank=True, null=True)),
                ('dec_d', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sky_catalog',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
