# Generated by Django 5.2.15 on 2026-06-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_app_settings_site_details_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('bortle_class', models.IntegerField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.IntegerField(default=1)),
                ('site_type', models.CharField(blank=True, choices=[('public_land', 'Public Land'), ('state_park', 'State Park'), ('national_park', 'National Park'), ('ida_certified', 'IDA Certified'), ('private', 'Private'), ('other', 'Other')], max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='accounts.site')),
                ('wikipedia_url', models.TextField(blank=True, null=True)),
                ('wikipedia_summary', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_credit', models.TextField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('maps_url', models.TextField(blank=True, null=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site_details',
            },
        ),
    ]
