# Generated by Django 5.2.15 on 2026-06-29 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sites_and_site_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField()),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='accounts.site')),
            ],
            options={
                'db_table': 'site_daily_scores',
                'ordering': ['-score_date', '-score'],
                'unique_together': {('site', 'score_date')},
            },
        ),
    ]
