# Generated by Django 5.2.15 on 2026-06-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_site_daily_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedailyscore',
            name='computed_at',
            field=models.DateTimeField(),
        ),
    ]
