# Generated by Django 5.2.15 on 2026-06-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_id_to_site_daily_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='NakedEyeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.TextField()),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'naked_eye_weights',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.TextField()),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'scoring_weights',
                'ordering': ['-weight'],
            },
        ),
    ]
