# Generated by Django 5.2.15 on 2026-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bortle_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bortlemodifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
